version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo:3.6.0
    ports:
      - "27017:27017"
    volumes:
      - dbvolume:/data
    environment: {
      AUTH: "no"
    }
    network_mode: host
  backend:
    container_name: backend
    build: ./backend/
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Vite takes care of most of this for us, but it's good practice for other backends
      - VITE_MONGO_HOST=mongodb
      - VITE_IP_ADDR=0.0.0.0
      - VITE_PORT=8080
      - VITE_LOGS_DIR=logs/

    depends_on: #This is a lie
      - mongodb
volumes:
  dbvolume: { }
