import { expect, afterEach } from 'vitest';
import { cleanup } from '@testing-library/react';
import matchers from '@testing-library/jest-dom/matchers';

/**
 * This file is auto-generated by pnpm create vite and auto-loaded by EVERY test
 * Only place things in here that you want to happen to EVERY test, otherwise place setup
 * inside each test file itself
 */


// extends Vitest's expect method with methods from react-testing-library
expect.extend(matchers);

// runs a cleanup after each test case (e.g. clearing jsdom)
afterEach(() => {
    cleanup();
});
